CREATE TABLE [dbo].[Reservation]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(25) NOT NULL,
	[Surname] VARCHAR(25) NOT NULL,
	[Email] VARCHAR(30) NOT NULL,
	[MobileNumber] VARCHAR (9) NOT NULL

)
